//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=Localhost;user id=root;password=;persistsecurityinfo=False;database=Servic" +
            "eXpress;Convert Zero Datetime=True")]
        public string cnxString {
            get {
                return ((string)(this["cnxString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 60")]
        public global::System.Drawing.Size sizeButtonSalon {
            get {
                return ((global::System.Drawing.Size)(this["sizeButtonSalon"]));
            }
            set {
                this["sizeButtonSalon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130, 60")]
        public global::System.Drawing.Size sizeButtonPedido {
            get {
                return ((global::System.Drawing.Size)(this["sizeButtonPedido"]));
            }
            set {
                this["sizeButtonPedido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int alturaPanelSalon {
            get {
                return ((int)(this["alturaPanelSalon"]));
            }
            set {
                this["alturaPanelSalon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PositionFormDetalle {
            get {
                return ((global::System.Drawing.Point)(this["PositionFormDetalle"]));
            }
            set {
                this["PositionFormDetalle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("428, 497")]
        public global::System.Drawing.Size SizeFormDetalle {
            get {
                return ((global::System.Drawing.Size)(this["SizeFormDetalle"]));
            }
            set {
                this["SizeFormDetalle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PositionFormMenu {
            get {
                return ((global::System.Drawing.Point)(this["PositionFormMenu"]));
            }
            set {
                this["PositionFormMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190, 570")]
        public global::System.Drawing.Size SizeFormMenu {
            get {
                return ((global::System.Drawing.Size)(this["SizeFormMenu"]));
            }
            set {
                this["SizeFormMenu"] = value;
            }
        }
    }
}
